# Generated by Django 5.1.5 on 2025-04-13 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TuitionModel',
            new_name='Tuition',
        ),
    ]
