# Generated by Django 5.1.5 on 2025-04-14 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0004_alter_tuition_class_name_delete_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='tuition',
            name='class_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tuition.class'),
        ),
    ]
