# Generated by Django 5.1.5 on 2025-05-02 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuition', '0006_alter_tuition_class_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuition',
            old_name='subjuct',
            new_name='subject',
        ),
    ]
